sudo: required

services:
  - docker

language: generic

install:
  - docker pull microsoft/dotnet:2-sdk-jessie
  - docker pull microsoft/dotnet:2-sdk

before_script:
  - sudo chmod +x ./ci-build.sh

script:
  - sudo ./ci-build.sh 1
  - sudo ./ci-build.sh 2
  - sudo ./ci-build.sh 3
  - sudo ./ci-build.sh 4
  - sudo ./ci-build.sh 5
  - sudo ./ci-build.sh 6
